CREATE OR REPLACE VIEW ods.vw_hm_energia AS
SELECT
  num_recibo,
  cod_suministro,
  tarifa,
  pot_contr,
  titularidad,
  distribuidor,
  fec_emision,
  fec_vencimiento,
  fec_lect_actual,
  fec_lect_anterior,
  per_consumo,
  ea_lec_act_hp,
  ea_lec_act_fp,
  ea_lec_act_tot,
  ea_lec_ant_hp,
  ea_lec_ant_fp,
  ea_lec_ant_tot,
  ea_consumo_hp,
  ea_consumo_fp,
  ea_consumo_tot,
  ea_pu_hp,
  ea_pu_fp,
  ea_prec_unit_tot,
  ea_importe_hp,
  ea_importe_fp,
  ea_importe_tot,
  pot_lect_act_hp,
  pot_lect_act_fp,
  pot_lect_ant_hp,
  pot_lect_ant_fp,
  pot_reg_hp,
  pot_reg_fp,
  pot_gen_fact,
  pot_gen_pu,
  pot_gen_importe,
  pot_dist_fact,
  pot_dist_pu,
  pot_dist_importe,
  pot_bt6_pu,
  pot_bt6_monto,
  er_lec_act,
  er_lec_ant,
  er_cons,
  er_fact,
  er_pu,
  er_importe,
  calif_cliente,
  dias_punta,
  horas_punta,
  factor_calif,
  cargo_fijo,
  mantenimiento,
  alumbrado,
  recup_energia,
  mora,
  reconexion,
  ajuste_tarifa,
  dist_factura,
  ajuste_alumb,
  otros_afectos,
  base_imponible,
  igv,
  tot_periodo,
  electrif_rural,
  comp_distribucion,
  comp_generadora,
  comp_interrup,
  comp_calidad,
  comp_frec_ant,
  comp_frec_des,
  comp_serv,
  comp_norma_tec,
  comp_deuda_ant,
  comp_deuda_meses,
  comp_dev_reclamo,
  comp_nota_deb_cred,
  comp_aporte_reemb,
  comp_otros_inafectos,
  comp_redondeo_act_pos,
  comp_redondeo_act_neg,
  costo_medio,
  total_a_pagar,
  valor_venta,
  deuda_anterior,
  devolucion,
  fecha_liquidacion,
  creation_user,
  creation_date,
  creation_ip,
  tabla_origen
FROM (
  /* 0) EXCEL primero */
  SELECT
    e.num_recibo::varchar(255)            AS num_recibo,
    e.cod_suministro::varchar(255)        AS cod_suministro,
    e.tarifa::varchar(255)                AS tarifa,
    e.pot_contr::varchar(255)             AS pot_contr,
    e.titularidad::varchar(255)           AS titularidad,
    e.distribuidor::varchar(255)          AS distribuidor,
    e.fec_emision::varchar(255)           AS fec_emision,
    e.fec_vencimiento::varchar(255)       AS fec_vencimiento,
    e.fec_lect_actual::varchar(255)       AS fec_lect_actual,
    e.fec_lect_anterior::varchar(255)     AS fec_lect_anterior,
    e.per_consumo::varchar(255)           AS per_consumo,
    e.ea_lec_act_hp::varchar(255)         AS ea_lec_act_hp,
    e.ea_lec_act_fp::varchar(255)         AS ea_lec_act_fp,
    e.ea_lec_act_tot::varchar(255)        AS ea_lec_act_tot,
    e.ea_lec_ant_hp::varchar(255)         AS ea_lec_ant_hp,
    e.ea_lec_ant_fp::varchar(255)         AS ea_lec_ant_fp,
    e.ea_lec_ant_tot::varchar(255)        AS ea_lec_ant_tot,
    e.ea_consumo_hp::varchar(255)         AS ea_consumo_hp,
    e.ea_consumo_fp::varchar(255)         AS ea_consumo_fp,
    e.ea_consumo_tot::varchar(255)        AS ea_consumo_tot,
    e.ea_pu_hp::varchar(255)              AS ea_pu_hp,
    e.ea_pu_fp::varchar(255)              AS ea_pu_fp,
    e.ea_prec_unit_tot::varchar(255)      AS ea_prec_unit_tot,
    e.ea_importe_hp::varchar(255)         AS ea_importe_hp,
    e.ea_importe_fp::varchar(255)         AS ea_importe_fp,
    e.ea_importe_tot::varchar(255)        AS ea_importe_tot,
    e.pot_lect_act_hp::varchar(255)       AS pot_lect_act_hp,
    e.pot_lect_act_fp::varchar(255)       AS pot_lect_act_fp,
    e.pot_lect_ant_hp::varchar(255)       AS pot_lect_ant_hp,
    e.pot_lect_ant_fp::varchar(255)       AS pot_lect_ant_fp,
    e.pot_reg_hp::varchar(255)            AS pot_reg_hp,
    e.pot_reg_fp::varchar(255)            AS pot_reg_fp,
    e.pot_gen_fact::varchar(255)          AS pot_gen_fact,
    e.pot_gen_pu::varchar(255)            AS pot_gen_pu,
    e.pot_gen_importe::varchar(255)       AS pot_gen_importe,
    e.pot_dist_fact::varchar(255)         AS pot_dist_fact,
    e.pot_dist_pu::varchar(255)           AS pot_dist_pu,
    e.pot_dist_importe::varchar(255)      AS pot_dist_importe,
    e.pot_bt6_pu::varchar(255)            AS pot_bt6_pu,
    e.pot_bt6_monto::varchar(255)         AS pot_bt6_monto,
    e.er_lec_act::varchar(255)            AS er_lec_act,
    e.er_lec_ant::varchar(255)            AS er_lec_ant,
    e.er_cons::varchar(255)               AS er_cons,
    e.er_fact::varchar(255)               AS er_fact,
    e.er_pu::varchar(255)                 AS er_pu,
    e.er_importe::varchar(255)            AS er_importe,
    e.calif_cliente::varchar(255)         AS calif_cliente,
    e.dias_punta::varchar(255)            AS dias_punta,
    e.horas_punta::varchar(255)           AS horas_punta,
    e.factor_calif::varchar(255)          AS factor_calif,
    e.cargo_fijo::varchar(255)            AS cargo_fijo,
    e.mantenimiento::varchar(255)         AS mantenimiento,
    e.alumbrado::varchar(255)             AS alumbrado,
    e.recup_energia::varchar(255)         AS recup_energia,
    e.mora::varchar(255)                  AS mora,
    e.reconexion::varchar(255)            AS reconexion,
    e.ajuste_tarifa::varchar(255)         AS ajuste_tarifa,
    e.dist_factura::varchar(255)          AS dist_factura,
    e.ajuste_alumb::varchar(255)          AS ajuste_alumb,
    e.otros_afectos::varchar(255)         AS otros_afectos,
    e.base_imponible::varchar(255)        AS base_imponible,
    e.igv::varchar(255)                   AS igv,
    e.tot_periodo::varchar(255)           AS tot_periodo,
    e.electrif_rural::varchar(255)        AS electrif_rural,
    e.comp_distribucion::varchar(255)     AS comp_distribucion,
    e.comp_generadora::varchar(255)       AS comp_generadora,
    e.comp_interrup::varchar(255)         AS comp_interrup,
    e.comp_calidad::varchar(255)          AS comp_calidad,
    e.comp_frec_ant::varchar(255)         AS comp_frec_ant,
    e.comp_frec_des::varchar(255)         AS comp_frec_des,
    e.comp_serv::varchar(255)             AS comp_serv,
    e.comp_norma_tec::varchar(255)        AS comp_norma_tec,
    e.comp_deuda_ant::varchar(255)        AS comp_deuda_ant,
    e.comp_deuda_meses::varchar(255)      AS comp_deuda_meses,
    e.comp_dev_reclamo::varchar(255)      AS comp_dev_reclamo,
    e.comp_nota_deb_cred::varchar(255)    AS comp_nota_deb_cred,
    e.comp_aporte_reemb::varchar(255)     AS comp_aporte_reemb,
    e.comp_otros_inafectos::varchar(255)  AS comp_otros_inafectos,
    e.comp_redondeo_act_pos::varchar(255) AS comp_redondeo_act_pos,
    e.comp_redondeo_act_neg::varchar(255) AS comp_redondeo_act_neg,
    e.costo_medio::varchar(255)           AS costo_medio,
    e.total_a_pagar::varchar(255)         AS total_a_pagar,
    e.valor_venta::varchar(255)           AS valor_venta,
    e.deuda_anterior::varchar(255)        AS deuda_anterior,
    e.devolucion::varchar(255)            AS devolucion,
    e.fecha_liquidacion::varchar(255)     AS fecha_liquidacion,
    NULL::varchar(255)                    AS creation_user,
    NULL::varchar(255)                    AS creation_date,
    NULL::varchar(255)                    AS creation_ip,
    'raw.excel_hm_consumo_energia'::varchar(255) AS tabla_origen
  FROM raw.excel_hm_consumo_energia e

  UNION ALL
  /* 1) ODS: sftp_hm_clientes_libres */
  SELECT
    s1.num_recibo::varchar(255),
    s1.cod_suministro::varchar(255),
    s1.tarifa::varchar(255),
    s1.pot_contr::varchar(255),
    s1.titularidad::varchar(255),
    s1.distribuidor::varchar(255),
    s1.fec_emision::varchar(255),
    s1.fec_vencimiento::varchar(255),
    s1.fec_lect_actual::varchar(255),
    s1.fec_lect_anterior::varchar(255),
    s1.per_consumo::varchar(255),
    s1.ea_lec_act_hp::varchar(255),
    s1.ea_lec_act_fp::varchar(255),
    s1.ea_lec_act_tot::varchar(255),
    s1.ea_lec_ant_hp::varchar(255),
    s1.ea_lec_ant_fp::varchar(255),
    s1.ea_lec_ant_tot::varchar(255),
    s1.ea_consumo_hp::varchar(255),
    s1.ea_consumo_fp::varchar(255),
    s1.ea_consumo_tot::varchar(255),
    s1.ea_pu_hp::varchar(255),
    s1.ea_pu_fp::varchar(255),
    s1.ea_prec_unit_tot::varchar(255),
    s1.ea_importe_hp::varchar(255),
    s1.ea_importe_fp::varchar(255),
    s1.ea_importe_tot::varchar(255),
    s1.pot_lect_act_hp::varchar(255),
    s1.pot_lect_act_fp::varchar(255),
    s1.pot_lect_ant_hp::varchar(255),
    s1.pot_lect_ant_fp::varchar(255),
    s1.pot_reg_hp::varchar(255),
    s1.pot_reg_fp::varchar(255),
    s1.pot_gen_fact::varchar(255),
    s1.pot_gen_pu::varchar(255),
    s1.pot_gen_importe::varchar(255),
    s1.pot_dist_fact::varchar(255),
    s1.pot_dist_pu::varchar(255),
    s1.pot_dist_importe::varchar(255),
    s1.pot_bt6_pu::varchar(255),
    s1.pot_bt6_monto::varchar(255),
    s1.er_lec_act::varchar(255),
    s1.er_lec_ant::varchar(255),
    s1.er_cons::varchar(255),
    s1.er_fact::varchar(255),
    s1.er_pu::varchar(255),
    s1.er_importe::varchar(255),
    s1.calif_cliente::varchar(255),
    s1.dias_punta::varchar(255),
    s1.horas_punta::varchar(255),
    s1.factor_calif::varchar(255),
    s1.cargo_fijo::varchar(255),
    s1.mantenimiento::varchar(255),
    s1.alumbrado::varchar(255),
    s1.recup_energia::varchar(255),
    s1.mora::varchar(255),
    s1.reconexion::varchar(255),
    s1.ajuste_tarifa::varchar(255),
    s1.dist_factura::varchar(255),
    s1.ajuste_alumb::varchar(255),
    s1.otros_afectos::varchar(255),
    s1.base_imponible::varchar(255),
    s1.igv::varchar(255),
    s1.tot_periodo::varchar(255),
    s1.electrif_rural::varchar(255),
    s1.comp_distribucion::varchar(255),
    s1.comp_generadora::varchar(255),
    s1.comp_interrup::varchar(255),
    s1.comp_calidad::varchar(255),
    s1.comp_frec_ant::varchar(255),
    s1.comp_frec_des::varchar(255),
    s1.comp_serv::varchar(255),
    s1.comp_norma_tec::varchar(255),
    s1.comp_deuda_ant::varchar(255),
    s1.comp_deuda_meses::varchar(255),
    s1.comp_dev_reclamo::varchar(255),
    s1.comp_nota_deb_cred::varchar(255),
    s1.comp_aporte_reemb::varchar(255),
    s1.comp_otros_inafectos::varchar(255),
    s1.comp_redondeo_act_pos::varchar(255),
    s1.comp_redondeo_act_neg::varchar(255),
    s1.costo_medio::varchar(255),
    s1.total_a_pagar::varchar(255),
    s1.valor_venta::varchar(255),
    s1.deuda_anterior::varchar(255),
    s1.devolucion::varchar(255),
    s1.fecha_liquidacion::varchar(255),
    s1.creation_user::varchar(255),
    s1.creation_date::varchar(255),
    s1.creation_ip::varchar(255),
    'ods.sftp_hm_clientes_libres'::varchar(255) AS tabla_origen
  FROM ods.sftp_hm_clientes_libres s1

  UNION ALL
  /* 2) ODS: sftp_hm_consumo_suministro */
  SELECT
    s2.num_recibo::varchar(255),
    s2.cod_suministro::varchar(255),
    s2.tarifa::varchar(255),
    s2.pot_contr::varchar(255),
    s2.titularidad::varchar(255),
    s2.distribuidor::varchar(255),
    s2.fec_emision::varchar(255),
    s2.fec_vencimiento::varchar(255),
    s2.fec_lect_actual::varchar(255),
    s2.fec_lect_anterior::varchar(255),
    s2.per_consumo::varchar(255),
    s2.ea_lec_act_hp::varchar(255),
    s2.ea_lec_act_fp::varchar(255),
    s2.ea_lec_act_tot::varchar(255),
    s2.ea_lec_ant_hp::varchar(255),
    s2.ea_lec_ant_fp::varchar(255),
    s2.ea_lec_ant_tot::varchar(255),
    s2.ea_consumo_hp::varchar(255),
    s2.ea_consumo_fp::varchar(255),
    s2.ea_consumo_tot::varchar(255),
    s2.ea_pu_hp::varchar(255),
    s2.ea_pu_fp::varchar(255),
    s2.ea_prec_unit_tot::varchar(255),
    s2.ea_importe_hp::varchar(255),
    s2.ea_importe_fp::varchar(255),
    s2.ea_importe_tot::varchar(255),
    s2.pot_lect_act_hp::varchar(255),
    s2.pot_lect_act_fp::varchar(255),
    s2.pot_lect_ant_hp::varchar(255),
    s2.pot_lect_ant_fp::varchar(255),
    s2.pot_reg_hp::varchar(255),
    s2.pot_reg_fp::varchar(255),
    s2.pot_gen_fact::varchar(255),
    s2.pot_gen_pu::varchar(255),
    s2.pot_gen_importe::varchar(255),
    s2.pot_dist_fact::varchar(255),
    s2.pot_dist_pu::varchar(255),
    s2.pot_dist_importe::varchar(255),
    s2.pot_bt6_pu::varchar(255),
    s2.pot_bt6_monto::varchar(255),
    s2.er_lec_act::varchar(255),
    s2.er_lec_ant::varchar(255),
    s2.er_cons::varchar(255),
    s2.er_fact::varchar(255),
    s2.er_pu::varchar(255),
    s2.er_importe::varchar(255),
    s2.calif_cliente::varchar(255),
    s2.dias_punta::varchar(255),
    s2.horas_punta::varchar(255),
    s2.factor_calif::varchar(255),
    s2.cargo_fijo::varchar(255),
    s2.mantenimiento::varchar(255),
    s2.alumbrado::varchar(255),
    s2.recup_energia::varchar(255),
    s2.mora::varchar(255),
    s2.reconexion::varchar(255),
    s2.ajuste_tarifa::varchar(255),
    s2.dist_factura::varchar(255),
    s2.ajuste_alumb::varchar(255),
    s2.otros_afectos::varchar(255),
    s2.base_imponible::varchar(255),
    s2.igv::varchar(255),
    s2.tot_periodo::varchar(255),
    s2.electrif_rural::varchar(255),
    s2.comp_distribucion::varchar(255),
    s2.comp_generadora::varchar(255),
    s2.comp_interrup::varchar(255),
    s2.comp_calidad::varchar(255),
    s2.comp_frec_ant::varchar(255),
    s2.comp_frec_des::varchar(255),
    s2.comp_serv::varchar(255),
    s2.comp_norma_tec::varchar(255),
    s2.comp_deuda_ant::varchar(255),
    s2.comp_deuda_meses::varchar(255),
    s2.comp_dev_reclamo::varchar(255),
    s2.comp_nota_deb_cred::varchar(255),
    s2.comp_aporte_reemb::varchar(255),
    s2.comp_otros_inafectos::varchar(255),
    s2.comp_redondeo_act_pos::varchar(255),
    s2.comp_redondeo_act_neg::varchar(255),
    s2.costo_medio::varchar(255),
    s2.total_a_pagar::varchar(255),
    s2.valor_venta::varchar(255),
    s2.deuda_anterior::varchar(255),
    s2.devolucion::varchar(255),
    s2.fecha_liquidacion::varchar(255),
    s2.creation_user::varchar(255),
    s2.creation_date::varchar(255),
    s2.creation_ip::varchar(255),
    'ods.sftp_hm_consumo_suministro'::varchar(255) AS tabla_origen
  FROM ods.sftp_hm_consumo_suministro s2

  UNION ALL
  /* 3) ODS: web_hm_indra_energia */
  SELECT
    w.num_recibo::varchar(255),
    w.cod_suministro::varchar(255),
    w.tarifa::varchar(255),
    w.pot_contr::varchar(255),
    w.titularidad::varchar(255),
    w.distribuidor::varchar(255),
    w.fec_emision::varchar(255),
    w.fec_vencimiento::varchar(255),
    w.fec_lect_actual::varchar(255),
    w.fec_lect_anterior::varchar(255),
    w.per_consumo::varchar(255),
    w.ea_lec_act_hp::varchar(255),
    w.ea_lec_act_fp::varchar(255),
    w.ea_lec_act_tot::varchar(255),
    w.ea_lec_ant_hp::varchar(255),
    w.ea_lec_ant_fp::varchar(255),
    w.ea_lec_ant_tot::varchar(255),
    w.ea_consumo_hp::varchar(255),
    w.ea_consumo_fp::varchar(255),
    w.ea_consumo_tot::varchar(255),
    w.ea_pu_hp::varchar(255),
    w.ea_pu_fp::varchar(255),
    w.ea_prec_unit_tot::varchar(255),
    w.ea_importe_hp::varchar(255),
    w.ea_importe_fp::varchar(255),
    w.ea_importe_tot::varchar(255),
    w.pot_lect_act_hp::varchar(255),
    w.pot_lect_act_fp::varchar(255),
    w.pot_lect_ant_hp::varchar(255),
    w.pot_lect_ant_fp::varchar(255),
    w.pot_reg_hp::varchar(255),
    w.pot_reg_fp::varchar(255),
    w.pot_gen_fact::varchar(255),
    w.pot_gen_pu::varchar(255),
    w.pot_gen_importe::varchar(255),
    w.pot_dist_fact::varchar(255),
    w.pot_dist_pu::varchar(255),
    w.pot_dist_importe::varchar(255),
    w.pot_bt6_pu::varchar(255),
    w.pot_bt6_monto::varchar(255),
    w.er_lec_act::varchar(255),
    w.er_lec_ant::varchar(255),
    w.er_cons::varchar(255),
    w.er_fact::varchar(255),
    w.er_pu::varchar(255),
    w.er_importe::varchar(255),
    w.calif_cliente::varchar(255),
    w.dias_punta::varchar(255),
    w.horas_punta::varchar(255),
    w.factor_calif::varchar(255),
    w.cargo_fijo::varchar(255),
    w.mantenimiento::varchar(255),
    w.alumbrado::varchar(255),
    w.recup_energia::varchar(255),
    w.mora::varchar(255),
    w.reconexion::varchar(255),
    w.ajuste_tarifa::varchar(255),
    w.dist_factura::varchar(255),
    w.ajuste_alumb::varchar(255),
    w.otros_afectos::varchar(255),
    w.base_imponible::varchar(255),
    w.igv::varchar(255),
    w.tot_periodo::varchar(255),
    w.electrif_rural::varchar(255),
    w.comp_distribucion::varchar(255),
    w.comp_generadora::varchar(255),
    w.comp_interrup::varchar(255),
    w.comp_calidad::varchar(255),
    w.comp_frec_ant::varchar(255),
    w.comp_frec_des::varchar(255),
    w.comp_serv::varchar(255),
    w.comp_norma_tec::varchar(255),
    w.comp_deuda_ant::varchar(255),
    w.comp_deuda_meses::varchar(255),
    w.comp_dev_reclamo::varchar(255),
    w.comp_nota_deb_cred::varchar(255),
    w.comp_aporte_reemb::varchar(255),
    w.comp_otros_inafectos::varchar(255),
    w.comp_redondeo_act_pos::varchar(255),
    w.comp_redondeo_act_neg::varchar(255),
    w.costo_medio::varchar(255),
    w.total_a_pagar::varchar(255),
    w.valor_venta::varchar(255),
    w.deuda_anterior::varchar(255),
    w.devolucion::varchar(255),
    w.fecha_liquidacion::varchar(255),
    w.creation_user::varchar(255),
    w.creation_date::varchar(255),
    w.creation_ip::varchar(255),
    'ods.web_hm_indra_energia'::varchar(255) AS tabla_origen
  FROM ods.web_hm_indra_energia w
) t;