version: '3.8'

services:
  # Base de datos PostgreSQL
  postgres:
    image: postgres:15
    container_name: scraper_postgres
    environment:
      POSTGRES_DB: scraper_db
      POSTGRES_USER: scraper_user
      POSTGRES_PASSWORD: scraper_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d
    networks:
      - scraper_network

  # Aplicación scraper
  scraper:
    build: .
    container_name: scraper_app
    depends_on:
      - postgres
    environment:
      # Variables de entorno para la aplicación
      - PYTHONPATH=/app
      - DOWNLOAD_PATH=/app/temp
      # Variables de base de datos
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=scraper_db
      - DB_USER=scraper_user
      - DB_PASSWORD=scraper_password
    volumes:
      - ./temp:/app/temp
      - ./.env:/app/.env
    networks:
      - scraper_network
    # Comando por defecto - mantener contenedor vivo para ejecución manual
    command: ["tail", "-f", "/dev/null"]

volumes:
  postgres_data:

networks:
  scraper_network:
    driver: bridge
