
CREATE TABLE ods.sftp_hm_pago_energia (
	contador_pedido int8 NULL,
	organizacion_compra varchar(250) NULL,
	grupo_compra int8 NULL,
	sociedad int8 NULL,
	nota_al_aprobador_char_40 varchar(250) NULL,
	nombre_pedido_char_40 varchar(250) NULL,
	material int8 NULL,
	texto_breve_del_material varchar(255) NULL,
	cantidad int8 NULL,
	fecha_de_entrega int8 NULL,
	ruc_proveedor int8 NULL,
	condicion_de_pago varchar(250) NULL,
	centro varchar(255) NULL,
	tipo_posicion varchar(250) NULL,
	tipo_imputacion varchar(250) NULL,
	centro_costo varchar(250) NULL,
	orden int8 NULL,
	elemento_pep varchar(250) NULL,
	area_funcional varchar(255) NULL,
	linea_negocio varchar(255) NULL,
	segmento varchar(255) NULL,
	grupo_segmento varchar(255) NULL,
	sub_segmento varchar(255) NULL,
	indicador_de_impuestos varchar(255) NULL,
	moneda varchar(250) NULL,
	licitacion varchar(250) NULL,
	precio_neto numeric(18, 2) NULL,
	solicitante varchar(255) NULL,
	uno varchar(255) NULL,
	dos varchar(255) NULL,
	tres varchar(255) NULL,
	cuatro varchar(255) NULL,
	cinco varchar(255) NULL,
	seis varchar(255) NULL,
	siete varchar(255) NULL,
	ocho varchar(255) NULL,
	nueve varchar(255) NULL,
	diez varchar(255) NULL,
	once varchar(255) NULL,
	proveedor_flm varchar(255) NULL,
	numero_de_hoja varchar(255) NULL,
	concesionario varchar(255) NULL,
	ruc_concesionario int8 NULL,
	tercero varchar(255) NULL,
	tipo_recibo varchar(255) NULL,
	zonal varchar(255) NULL,
	cliente varchar(255) NULL,
	numero_documento varchar(255) NULL,
	numero_suministro varchar(255) NULL,
	nombre_local varchar(255) NULL,
	direccion_local varchar(255) NULL,
	servicio varchar(255) NULL,
	recibo varchar(255) NOT NULL,
	original varchar(255) NULL,
	tipo_recibo_2 varchar(255) NULL,
	tipo_voucher varchar(255) NULL,
	porcentaje_voucher varchar(255) NULL,
	importe_voucher numeric(18, 2) NULL,
	base_imponible numeric(18, 2) NULL,
	pago_inafectos numeric(18, 2) NULL,
	valor_venta_total numeric(18, 2) NULL,
	igv numeric(18, 2) NULL,
	total_pagado numeric(18, 2) NULL,
	fecha_emision date NULL,
	fecha_vencimiento date NULL,
	periodo_consumo varchar(255) NULL,
	mes_facturacion varchar(255) NULL,
	periodo_reporte varchar(255) NULL,
	observacion varchar(255) NULL,
	clase varchar(255) NULL,
	numero_sap varchar(255) NULL,
	neteo varchar(255) NULL,
	cesta varchar(255) NULL,
	orden_de_compra varchar(255) NULL,
	certificacion varchar(255) NULL,
	soles_comparativo int8 NULL,
	unnamed_76 varchar(250) NULL,
	codigo_unico_local int8 NULL,
	cuenta int8 NULL,
	fe_valor date NULL,
	mon varchar(250) NULL,
	importe_en_md numeric(18, 2) NULL,
	texto text NULL,
	asignacion varchar(250) NULL,
	deuda_mes_anterior numeric(18, 2) NULL,
	total_pagado_recibo int8 NULL,
	creation_user varchar(100) DEFAULT (((COALESCE(inet_client_addr()::text, 'local'::text) || '-'::text) || CURRENT_USER::text)) NULL,
	creation_date timestamp(0) DEFAULT clock_timestamp()::timestamp(0) without time zone NULL,
	creation_ip inet DEFAULT inet_client_addr() NULL,
	CONSTRAINT liq_recibos_de_luz_pk PRIMARY KEY (recibo)
);