CREATE TABLE raw.ge_grupo_electrogeno (
    task_id varchar(255) NOT NULL,
    site_id varchar(255) NOT NULL,
    sub_wo_id varchar(255) NOT NULL,
    codigo_unico_de_ge text NULL,
    marca_de_grupo_electrogeno text NULL,
    modelo_de_grupo_electrogeno text NULL,
    serie_de_grupo_electrogeno text NULL,
    potenc_grupo_electr_kva text NULL,
    fases text NULL,
    voltaje_de_grupo_electrogeno_v text NULL,
    ge_rotula_cod_unico_caso_que text NULL,
    marca_motor text NULL,
    modelo_motor text NULL,
    serie_motor text NULL,
    capacidad_hp_motor text NULL,
    fecha_ultimo_cambio_filtro text NULL,
    fecha_ultimo_cambio_filtro_aceite_diesel_refrig text NULL,
    fecha_ultimo_cambio_refrig text NULL,
    ultimo_cambio_filtro_aceite_ha text NULL,
    ultimo_cambio_filtro_petrol_ha text NULL,
    ultimo_cambio_filtro_refrig_ha text NULL,
    ultimo_cambio_filtro_aire_ha text NULL,
    horometro text NULL,
    limpieza_externa text NULL,
    verifi_operat_sujeta_restri text NULL,
    verifi_nivel_refrig_radiad text NULL,
    fecha_de_cambio_de_faja text NULL,
    limp_pintad_ventil text NULL,
    verifi_estado_tinas_aletas text NULL,
    limpia_obstru_sondeo_radiad text NULL,
    verifi_estado_termos text NULL,
    verif_correc_fugas_combus text NULL,
    medir_nivel_aceite_carter text NULL,
    presion_aceite_motor text NULL,
    verifi_func_arranc_ajuste text NULL,
    verifi_func_actuad_bomba text NULL,
    verifi_func_gobern_otros text NULL,
    verifi_func_altern_carga text NULL,
    temperatura_del_motor text NULL,
    resumi_aceite_alguna_parte text NULL,
    observacion text NULL,
    marca_de_generador text NULL,
    modelo_de_generador text NULL,
    potencia_kw_de_generador text NULL,
    limpieza_general text NULL,
    verifi_circul_aire_fresco text NULL,
    verif_ruidos_anorma_vibrac text NULL,
    verifi_operat_resist_deshum text NULL,
    verificar_rejillas_protectoras text NULL,
    verifi_que_radiad_no_tenga text NULL,
    ge_tiene_partes_corroidas text NULL,
    tiene_tanque_externo text NULL,
    observacion_del_ge text NULL,
    cod_grupo_electr_asoc_bat text NULL,
    cantid_bat_arranq_conect_ge text NULL,
    marca text NULL,
    capacidad_ah text NULL,
    cantidad_de_placas text NULL,
    fecha_ultimo_cambio_anotad_bat1 text NULL,
    fecha_ultimo_cambio_anotad_bat2 text NULL,
    fecha_ultimo_cambio_anotad_bat3 text NULL,
    fecha_ultimo_cambio_anotad_bat4 text NULL,
    voltaje_bat1_vdc text NULL,
    voltaje_bat2_vdc text NULL,
    voltaj_bat3_vdc_caso_si_existi text NULL,
    voltaj_bat4_vdc_caso_si_existi text NULL,
    verifi_valore_carga_bat text NULL,
    limp_ajuste_cables_bornes_bat text NULL,
    carga_de_bat_arranqueamp text NULL,
    ge_etiquetado_cod_unico text NULL,
    observacion1 text NULL,
    fechacarga timestamp(0) NOT NULL
);

CREATE INDEX raw_ge_grupo_electrogeno_fechacarga_idx
ON raw.ge_grupo_electrogeno USING btree (fechacarga);
