CREATE TABLE raw.radio_6_12_18_bas_cf_bb (
    task_id varchar(255) NOT NULL,
    site_id varchar(255) NOT NULL,
    sub_wo_id varchar(255) NOT NULL,
    marca text NULL,
    limp_filtro_gabine text NULL,
    temperatura text NULL,
    verifi_alarma_puerta_abiert text NULL,
    verificacion_sellado_gabinete text NULL,
    observacion text NULL,
    sistema_al_que_alimenta text NULL,
    marca1 text NULL,
    modelo text NULL,
    capacidad_itm_de_banda_base text NULL,
    verificar_etiquetado_de_itm text NULL,
    cantidad_de_rectificadores text NULL,
    ajuste_de_conectores_de_itm text NULL,
    capacidad_amp text NULL,
    carga_actual_de_tecnologia_3g text NULL,
    carga_actual_de_tecnologia_4g text NULL,
    carga_actual_de_rrus_3g text NULL,
    carga_actual_de_rrus_4g text NULL,
    limpieza_y_ajustes_de_modulos text NULL,
    limpieza_y_o_cambio_de_filtros text NULL,
    verifi_chapas_llaves_puerta text NULL,
    observ text NULL,
    numero_de_banco text NULL,
    marca2 text NULL,
    modelo1 text NULL,
    capacidad_ah text NULL,
    estado_bat_elem_anexos_puentes text NULL,
    observ_que_bat_celdas_no text NULL,
    limpieza_general text NULL,
    observacion1 text NULL,
    fechacarga timestamp(0) NOT NULL
);

CREATE INDEX raw_radio_6_12_18_bas_cf_bb_fechacarga_idx
ON raw.radio_6_12_18_bas_cf_bb USING btree (fechacarga);