CREATE TABLE raw.ge_transferencia_con_carga (
    task_id varchar(255) NOT NULL,
    site_id varchar(255) NOT NULL,
    sub_wo_id varchar(255) NOT NULL,
    codigo_de_grupo_electrogeno text NULL,
    codigo_de_tta text NULL,
    ge_esta_en_automatico_o_manual text NULL,
    ge_cuenta_con_controlador text NULL,
    tta_cuenta_con_controlador text NULL,
    tta_averiado text NULL,
    tiene_bat_fecha_vigent text NULL,
    fecha_de_ultimo_cambio_de_bat text NULL,
    revisa_nivel_calida_aceite text NULL,
    se_confir_que_bat_respal text NULL,
    se_reviso_itm_bat_conex_batier text NULL,
    trifasico_o_monofasico text NULL,
    frecuencia_hz text NULL,
    voltaje_r_s_red_comercial_v text NULL,
    voltaje_s_t_red_comercial_v text NULL,
    voltaje_t_r_red_comercial_v text NULL,
    ir_red_comercial_a text NULL,
    is_red_comercial_a text NULL,
    it_red_comercial_a text NULL,
    observacion text NULL,
    se_bajo_itm_ac text NULL,
    tiempo_desde_corte_energi text NULL,
    tiempo_desde_encend_ge_hasta text NULL,
    frecuencia_con_ge text NULL,
    voltaje_r_s_en_ge_v text NULL,
    voltaje_s_t_en_ge_v text NULL,
    voltaje_t_r_en_ge_v text NULL,
    ir_de_ge_a text NULL,
    is_de_ge_a text NULL,
    it_de_ge_a text NULL,
    alarma_corte_red_sale_noc text NULL,
    etique_alarma_que_sale_noc text NULL,
    alarma_sale_localm_cuadro_fza text NULL,
    alarma_ge_operan_sale_noc text NULL,
    etique_alarma_que_sale_noc_1 text NULL,
    alarma_sale_localm_cuadro_fza_1 text NULL,
    tiempo_desde_subida_itm_hasta text NULL,
    tiempo_desde_encend_ge_hasta_2 text NULL,
    observacion_prueba text NULL,
    ge_entro_sin_problemas text NULL,
    algun_parametro_fuera_de_rango text NULL,
    conclusiones_generales text NULL,
    foto_ge_tta_se_vea_que_grupo text NULL,
    fechacarga timestamp(0) NOT NULL
);

CREATE INDEX raw_ge_transferencia_con_carga_fechacarga_idx
ON raw.ge_transferencia_con_carga USING btree (fechacarga);
