
CREATE TABLE raw.fs_mm_base_de_sitios (
	codigo_unico varchar(250) NULL,
	nombre_local varchar(250) NULL,
	direccion varchar(400) NULL,
	latitud varchar(250) NULL,
	longitud varchar(250) NULL,
	ubigeo varchar(250) NULL,
	departamento varchar(250) NULL,
	provincia varchar(250) NULL,
	distrito varchar(250) NULL,
	tipo_local varchar(250) NULL,
	proveedor_flm varchar(250) NULL,
	atencion varchar(250) NULL,
	zona varchar(250) NULL,
	tipo_zona_flm varchar(250) NULL,
	propietario_de_torre varchar(250) NULL,
	propietario_de_piso varchar(250) NULL,
	tipo_estacion varchar(250) NULL,
	tipo_torre varchar(250) NULL,
	clasificacion_instalacion varchar(250) NULL,
	fecha_puesta_en_servicio varchar(250) NULL,
	bucket varchar(250) NULL,
	sla varchar(250) NULL,
	tipo_vip varchar(250) NULL,
	criticidad_local varchar(250) NULL,
	observacion varchar(250) NULL,
	priorizacion varchar(250) NULL,
	ubigeotoa varchar(250) NULL
);