default:
  # Valores que se pueden sobreescribir con variables de entorno o conexiones de Airflow.
  download_path: "./tmp"
  max_iframe_attempts: 60
  max_status_attempts: 60
  options_to_select: "CM,OPM"
  date_mode: 2
  date_from: "2025-09-01"
  date_to: "2025-09-10"
  gde_output_filename: "Console_GDE_export.xlsx"
  dynamic_checklist_output_filename: "DynamicChecklist_SubPM.xlsx"
  export_overwrite_files: true
  proxy: "telefonica01.gp.inet:8080"
