
CREATE TABLE ods.sftp_hd_toa (
	tecnico text NULL,
	id_recurso int4 NULL,
	nro_toa text NOT NULL,
	subtipo_de_actividad text NULL,
	numero_de_peticion text NULL,
	fecha_de_cita date NULL,
	sla_inicio timestamp NULL,
	sla_fin timestamp NULL,
	localidad text NULL,
	direccion text NULL,
	direccion_polar_x numeric NULL,
	direccion_polar_y numeric NULL,
	nombre_cliente text NULL,
	hora_de_asignacion_de_actividad timestamp NULL,
	fecha_de_registro_de_actividad_toa timestamp NULL,
	notas text NULL,
	codigo_de_cliente text NULL,
	fecha_hora_de_cancelacion timestamp NULL,
	empresa text NULL,
	bucket_inicial text NULL,
	usuario_iniciado text NULL,
	nombre_distrito text NULL,
	sistema_origen text NULL,
	id_del_ticket text NULL,
	quiebres text NULL,
	fecha_de_inicio_pint timestamp NULL,
	inicio_pr1 timestamp NULL,
	fin_pr1 timestamp NULL,
	fin_pr2 timestamp NULL,
	inicio_pr2 timestamp NULL,
	fin_pr3 timestamp NULL,
	inicio_pr3 timestamp NULL,
	fin_pr4 timestamp NULL,
	inicio_pr4 timestamp NULL,
	motivo_pr1 text NULL,
	motivo_pr2 text NULL,
	motivo_pr3 text NULL,
	motivo_pr4 text NULL,
	nombre_local text NULL,
	tipo_de_local text NULL,
	zona_geografica text NULL,
	zona text NULL,
	estado_toa text NULL,
	duracion_pr1 text NULL,
	duracion_pr2 text NULL,
	duracion_pr3 text NULL,
	duracion_pr4 text NULL,
	estado text NULL,
	codigo_completado_reparacion_y_preventivo_cable text NULL,
	cliente_acepta_solucion_anticipada_de_reclamo text NULL,
	averia_efectiva_marca_sar_t text NULL,
	creation_user varchar(100) DEFAULT (((COALESCE(inet_client_addr()::text, 'local'::text) || '-'::text) || CURRENT_USER::text)) NULL,
	creation_date timestamp(0) DEFAULT clock_timestamp()::timestamp(0) without time zone NULL,
	creation_ip inet DEFAULT inet_client_addr() NULL,
	CONSTRAINT pk_sftp_hd_toa PRIMARY KEY (nro_toa)
);