CREATE TABLE raw.clima_evaporador (
  task_id                                         varchar(255) NOT NULL,
  site_id                                         varchar(255) NOT NULL,
  sub_wo_id                                       varchar(255) NOT NULL,

  codigo_unico_aire_intervenir                    text NULL,
  identificacion_nombre_aa                        text NULL,
  cantidad_total_aa_sala                          text NULL,
  tipo_aa                                         text NULL,
  tipo_flujo                                      text NULL,
  marca_aa                                        text NULL,
  modelo_aa                                       text NULL,
  serie_aa                                        text NULL,
  estado_aa                                       text NULL,
  voltaje_aa                                      text NULL,
  refrigerante                                    text NULL,
  capacidad_tr                                    text NULL,
  ubicacion_ue                                    text NULL,
  comparte_ducto_con_otros_aa                     text NULL,
  consumo_ue_fase_r                               text NULL,
  consumo_ue_fase_s                               text NULL,
  consumo_ue_fase_t                               text NULL,
  observacion_ue                                  text NULL,
  compresores_en_unidad_evaporadora               text NULL,
  numero_compresores                              text NULL,
  porcentaje_carga                                text NULL,
  temp_inyeccion_c                                text NULL,
  temp_retorno_c                                  text NULL,
  temp_seteo_c                                    text NULL,
  revision_motor_fan_y_giro                       text NULL,
  limpieza_turbinas_ventilador_evap               text NULL,
  medidas_filtro_y_cantidad_cm                    text NULL,
  filtro_aire_limpio_o_cambiado                   text NULL,
  lavado_serpentin_alki_klean                     text NULL,
  consumo_motor_ventilador_ir                     text NULL,
  consumo_motor_ventilador_is                     text NULL,
  consumo_motor_ventilador_it                     text NULL,
  limpieza_ajuste_terminales_ue_con_motoventilador text NULL,
  rev_tension_correas_rodamientos_switch_seguridad text NULL,
  revision_ajuste_lubricacion_alineamiento_poleas text NULL,
  observacion_filtros_rodamientos_poleas_correas_giro_ventilador text NULL,
  rev_fusibles_conexiones_electricas              text NULL,
  rev_calibracion_termostatos_humidificadores     text NULL,
  sala_gestionada_alarma_alta_temperatura         text NULL,
  temp_alarma_seteada_c                           text NULL,
  temp_ambiente_c                                 text NULL,
  prueba_equipo_principal_y_respaldo              text NULL,
  limpieza_ajuste_terminales_ue                   text NULL,
  observacion_sist_electrico                      text NULL,
  limpieza_bandeja_condensado_y_drenaje           text NULL,
  agua_fluye_normal_en_bandeja                    text NULL,
  mantenimiento_bomba_condensado                  text NULL,
  observacion_drenaje                             text NULL,
  cantidad_compresores_totales_aa                 text NULL,

  -- Compresor 1
  capacidad_compresor_1_tr                        text NULL,
  ubicacion_compresor_1                           text NULL,
  tipo_compresor_1                                text NULL,
  tipo_alimentacion_compresor_1                   text NULL,
  voltaje_compresor_1                             text NULL,
  estado_compresor_1                              text NULL,
  presion_baja_circuito_1                         text NULL,
  presion_alta_circuito_1                         text NULL,
  consumo_compresor_1_ir                          text NULL,
  consumo_compresor_1_is                          text NULL,
  consumo_compresor_1_it                          text NULL,
  observacion_compresor_1                         text NULL,

  -- Compresor 2
  capacidad_compresor_2_tr                        text NULL,
  ubicacion_compresor_2                           text NULL,
  tipo_compresor_2                                text NULL,
  marca_compresor_1                               text NULL, -- viene así en el formulario
  tipo_alimentacion_compresor_2                   text NULL,
  marca_compresor_2                               text NULL,
  voltaje_compresor_2                             text NULL,
  estado_compresor_2                              text NULL,
  presion_baja_circuito_2                         text NULL,
  presion_alta_circuito_2                         text NULL,
  consumo_compresor_2_ir                          text NULL,
  consumo_compresor_2_is                          text NULL,
  consumo_compresor_2_it                          text NULL,
  observacion_compresor_2                         text NULL,

  fechacarga                                      timestamp(0) NOT NULL
);

CREATE INDEX raw_clima_evaporador_fechacarga_idx
ON raw.clima_evaporador USING btree (fechacarga);
