CREATE TABLE raw.clima_condensador (
  task_id                                         varchar(255) NOT NULL,
  site_id                                         varchar(255) NOT NULL,
  sub_wo_id                                       varchar(255) NOT NULL,

  marca_compresor_1                               text NULL,
  marca_compresor_2                               text NULL,
  codigo_unico_aire_intervenir                    text NULL,
  identificacion_nombre_aa                        text NULL,
  cantidad_condensadores_total_aa                 text NULL,
  nro_unidad_condensadora_intervenir_1            text NULL,
  tipo_aa                                         text NULL,
  marca_aa                                        text NULL,
  modelo_aa                                       text NULL,
  serie_aa                                        text NULL,
  estado_aa                                       text NULL,
  voltaje_aa                                      text NULL,
  nro_unidad_condensadora_intervenir_2            text NULL,
  refrigerante                                    text NULL,
  capacidad_tr                                    text NULL,
  ubicacion_uc                                    text NULL,
  consumo_uc_fase_r                               text NULL,
  consumo_uc_fase_s                               text NULL,
  consumo_uc_fase_t                               text NULL,
  observacion                                     text NULL,
  compresores_en_unidad_condensadora              text NULL,
  numero_compresores                              text NULL,
  rev_tension_correas_rodamientos_switch_seguridad text NULL,
  cantidad_motor_ventilador_uc                    text NULL,
  tiene_motoventilador_averiado                   text NULL,
  alimentacion_motor_ventilador                   text NULL,
  consumo_motor_ventilador_ir                     text NULL,
  consumo_motor_ventilador_is                     text NULL,
  consumo_motor_ventilador_it                     text NULL,
  temp_salida_unidad_condensadora_c               text NULL,
  tiene_visor_humedad                             text NULL,
  visor_refleja_gotas_humedad                     text NULL,
  tiene_presostato_baja                           text NULL,
  tiene_presostato_alta                           text NULL,
  rev_perdidas_aceite                             text NULL,
  revision_estado_valvulas_solen_filtro_presostato text NULL,
  observacion_condensador                         text NULL,
  recarga_gas_baja_presion_o_fuga                 text NULL,
  cantidad_refrigerante_recargado_kg              text NULL,
  peso_balon_antes_recarga_kg                     text NULL,
  peso_balon_despues_recarga_kg                   text NULL,
  cantidad_compresores_totales_aa                 text NULL,

  capacidad_compresor_1_tr                        text NULL,
  ubicacion_compresor_1                           text NULL,
  tipo_compresor_1                                text NULL,
  tipo_alimentacion_compresor_1                   text NULL,
  voltaje_compresor_1                             text NULL,
  estado_compresor_1                              text NULL,
  presion_baja_circuito_1                         text NULL,
  presion_alta_circuito_1                         text NULL,
  consumo_compresor_1_ir                          text NULL,
  consumo_compresor_1_is                          text NULL,
  consumo_compresor_1_it                          text NULL,
  observacion_compresor_1                         text NULL,

  capacidad_compresor_2_tr                        text NULL,
  ubicacion_compresor_2                           text NULL,
  tipo_compresor_2                                text NULL,
  tipo_alimentacion_compresor_2                   text NULL,
  voltaje_compresor_2                             text NULL,
  estado_compresor_2                              text NULL,
  presion_baja_circuito_2                         text NULL,
  presion_alta_circuito_2                         text NULL,
  consumo_compresor_2_ir                          text NULL,
  consumo_compresor_2_is                          text NULL,
  consumo_compresor_2_it                          text NULL,
  observacion_compresor_2                         text NULL,

  fechacarga                                      timestamp(0) NOT NULL
);

CREATE INDEX raw_clima_condensador_fechacarga_idx
ON raw.clima_condensador USING btree (fechacarga);
