CREATE TABLE raw.clima (
  task_id                                   varchar(255) NOT NULL,
  site_id                                   varchar(255) NOT NULL,
  sub_wo_id                                 varchar(255) NOT NULL,

  -- Bloque 1: datos generales equipo / condensador
  ident_nombre_aa_1                         text NULL,
  marca_aa_1                                text NULL,
  modelo_aa_1                               text NULL,
  serie_aa_1                                text NULL,
  refrigerante_1                            text NULL,
  capacidad_tr_1                            text NULL,
  codigo_numero_equipo_1                    text NULL,
  ubicacion_1                               text NULL,
  numero_condensador_1                      text NULL,
  observacion_1                             text NULL,

  -- Bloque 2: condensador / motores / compresores (parte 1)
  ident_nombre_aa_2                         text NULL,
  numero_condensador_2                      text NULL,
  limpieza_turbinas_motores                 text NULL,
  rev_correas_rodamientos_switch_1          text NULL,
  consumo_motor_ventilador_ir_is_1          text NULL,
  verificacion_temp_inyeccion_retorno_1     text NULL,
  rev_ajuste_alineamiento_transmision_1     text NULL,
  rev_nivel_aceite_refrigerante_1           text NULL,
  rev_switch_seguridad_1                    text NULL,
  consumo_electrico_compresor1_1            text NULL,
  consumo_electrico_compresor2_1            text NULL,
  observacion_2                             text NULL,
  limpieza_motor_ventiladores_1             text NULL,
  limpieza_serpentin_1                      text NULL,
  rev_rodamientos_1                         text NULL,
  consumo_electrico_condensador_motor1      text NULL,
  consumo_electrico_condensador_motor2      text NULL,
  rev_alineamiento_tensado_fajas_1          text NULL,
  presion_baja_circuito1_1                  text NULL,
  presion_baja_circuito2_1                  text NULL,
  presion_alta_circuito1_1                  text NULL,
  presion_alta_circuito2_1                  text NULL,
  rev_perdidas_aceite_1                     text NULL,
  lavado_evaporadores_1                     text NULL,
  rev_estado_valvulas_filtro_presostato_1   text NULL,
  recarga_gas_baja_presion_o_fuga_1         text NULL,
  observacion_3                             text NULL,

  -- Bloque 3: pruebas de compresor
  ident_nombre_aa_3                         text NULL,
  numero_compresor                          text NULL,
  ubicacion_compresor                       text NULL,
  tipo_compresor                            text NULL,
  consumo_compresor_irs_ist_itr             text NULL,
  consumo_compresor_arranque_irs_ist_itr    text NULL,
  resistencia_bobinas_ohm                   text NULL,
  medicion_continuidad_bobinas              text NULL,
  observacion_4                             text NULL,

  -- Bloque 4: filtros / humidificador / bandeja / ventiladores
  ident_nombre_aa_4                         text NULL,
  numero_equipo_2                           text NULL,
  tipo_equipo_2                             text NULL,
  marca_equipo_2                            text NULL,
  modelo_equipo_2                           text NULL,
  serie_equipo_2                            text NULL,
  capacidad_tr_2                            text NULL,
  ubicacion_equipo_2                        text NULL,
  observacion_5                             text NULL,
  limpieza_cambio_filtro                    text NULL,
  rev_switch_filtros_tapados                text NULL,
  medidas_filtro_y_cantidad                 text NULL,
  lavado_evaporadores_2                     text NULL,
  limpieza_deshumidificador                 text NULL,
  limpieza_bandeja_bomba_condensado         text NULL,
  limpieza_bandeja                          text NULL,
  calidad_agua                              text NULL,
  rev_valvula_flotador_drenaje_lampara      text NULL,
  consumo_electrico_humidificador           text NULL,
  limpieza_pruebas_proteccion_humidificador text NULL,
  limpieza_turbinas_2                       text NULL,
  rev_correas_rodamientos_switch_2          text NULL,
  consumo_motor_ventilador_ir_is_2          text NULL,
  verificacion_temp_inyeccion_retorno_2     text NULL,
  rev_ajuste_alineamiento_poleas_anclaje    text NULL,
  rev_ajuste_alineamiento_transmision_2     text NULL,
  observacion_6                             text NULL,
  rev_reparacion_serpentin_obstruccion_1    text NULL,
  rev_perdidas_aceite_2                     text NULL,
  observacion_7                             text NULL,
  rev_reparacion_serpentin_obstruccion_2    text NULL,
  limpieza_bandeja_condensado_2             text NULL,
  presion_succion_circuito1                 text NULL,
  presion_succion_circuito2                 text NULL,
  presion_descarga_circuito1                text NULL,
  presion_descarga_circuito2                text NULL,
  rev_perdidas_aceite_3                     text NULL,
  lavado_evaporadores_3                     text NULL,
  observacion_8                             text NULL,

  -- Bloque 5: sistema eléctrico / control / alarmas
  ident_nombre_aa_5                         text NULL,
  rev_fusibles_conexiones_electricas        text NULL,
  rev_calibracion_termostatos_humidificadores text NULL,
  verificacion_protecciones_reles_contactores text NULL,
  rev_sistema_operacion_secuencial_control  text NULL,
  alarma_termostato_alta_temp               text NULL,
  sala_con_alarma_alta_temp                 text NULL,
  temp_seteada_c                            text NULL,
  temp_ambiente_c                           text NULL,
  prueba_equipo_principal_respaldo          text NULL,
  observacion_9                             text NULL,

  fechacarga                                timestamp(0) NOT NULL
);

CREATE INDEX raw_clima_fechacarga_idx
ON raw.clima USING btree (fechacarga);
