
-- ============================================================================
-- 3) CF - CUADRO DE FUERZA
-- ============================================================================
CREATE TABLE IF NOT EXISTS raw.cf_cuadro_de_fuerza (
    task_id                             VARCHAR(255) NOT NULL,
    site_id                             VARCHAR(255) NOT NULL,
    sub_wo_id                           VARCHAR(255) NOT NULL,

    nom_cuadro_fza_ejempl_cabece        TEXT,
    nom_sala_ubic_cuadro_fza            TEXT,
    codigo_de_equipo                    TEXT,
    marca_de_cuadro_fuerza              TEXT,
    modelo_de_cuadro_de_fuerza          TEXT,
    modelo_de_unidad_rectificadora      TEXT,
    cuadro_fza_rotula_cod_unico_eq      TEXT,
    cantid_banco_bat_conect_cf          TEXT,
    capaci_total_banco_bat_conect       TEXT,
    consumo_real_de_cf_ampdc            TEXT,
    capaci_maxima_cuadro_fza            TEXT,
    capaci_actual_real_cuadro_fza       TEXT,
    cantidad_de_bastidores              TEXT,
    cantid_modulo_rectif                TEXT,
    anio_de_instalacion                 TEXT,
    estado                              TEXT,
    limpieza_y_o_cambio_de_filtros      TEXT,
    ajuste_de_terminales                TEXT,
    verif_alarma_extern                 TEXT,
    medici_corrie_unidad_baja_amp       TEXT,
    medici_voltaj_unidad_baja_v         TEXT,
    temper_camara_termog_pirome         TEXT,
    limp_ajuste_pintad_rotula_cada      TEXT,
    senali_peligr_acceso_restri         TEXT,
    estado_chapas_llaves_puerta         TEXT,
    limp_ajuste_pintad_barras           TEXT,
    verif_operac_redund                 TEXT,
    arranque_lento                      TEXT,
    alta_eficiencia                     TEXT,
    comparticion_de_carga               TEXT,
    limita_corrie_bat                   TEXT,
    limita_potenc_rectif                TEXT,
    compro_monito_local                 TEXT,
    actual_diagra_unifil                TEXT,
    regist_valor_ajuste_protec          TEXT,
    eq_rotula_cod_eq_nom_cuadro         TEXT,
    confir_correc_conex_cable           TEXT,
    nom_person_noc_energi_quien_se      TEXT,
    alarma_cableada_falla_de_red        TEXT,
    la_alarma_se_reflejo_en_el_noc      TEXT,
    alarma_cablea_grupo_electr          TEXT,
    alarma_se_reflej_noc_1              TEXT,
    alarma_cablea_falla_grupo           TEXT,
    alarma_se_reflej_noc_2              TEXT,
    alarma_cablea_alta_temper           TEXT,
    alarma_se_reflej_noc_3              TEXT,
    alarma_cablea_falla_rectif          TEXT,
    alarma_se_reflej_noc_4              TEXT,
    alarma_cablea_bajo_voltaj_bat       TEXT,
    alarma_se_reflej_noc_5              TEXT,
    alarma_cablea_bajo_nivel            TEXT,
    alarma_se_reflej_noc_6              TEXT,
    cuadro_fza_que_perten_modulo        TEXT,
    tipo_de_modulo_de_gestion           TEXT,
    marca_de_modulo_de_gestion          TEXT,
    modelo_de_modulo_de_gestion         TEXT,
    limp_ajuste_calibr_compon           TEXT,
    prueba_de_funcionamiento            TEXT,
    observacion                         TEXT,
    cod_prueba_alarma_noc               TEXT,
    fechacarga                          TIMESTAMP(0) NOT NULL
);
