
CREATE TABLE public.log_sp (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	id_sp int4 NULL,
	sp varchar(125) NULL,
	inicio timestamp(0) NULL,
	fin timestamp(0) DEFAULT clock_timestamp()::timestamp(0) without time zone NULL,
	inserted int4 NULL,
	updated int4 NULL,
	deleted int4 NULL,
	"nulls" int4 NULL,
	estado varchar(50) NULL,
	msj_error text NULL,
	usr_cre text DEFAULT CURRENT_USER NULL,
	CONSTRAINT log_sp_pkey PRIMARY KEY (id)
);
CREATE INDEX ix_log_sp_norm_fin_id ON public.log_sp USING btree (regexp_replace(btrim(lower((sp)::text)), '\\(\\)$'::text, ''::text), fin DESC, id DESC);