
CREATE TABLE ods.fs_hm_base_de_sitios (
	codigo_unico varchar(120) NULL,
	nombre_local varchar(200) NULL,
	direccion varchar(350) NULL,
	latitud numeric(11, 8) NULL,
	longitud numeric(11, 8) NULL,
	ubigeo varchar(10) NULL,
	departamento varchar(120) NULL,
	provincia varchar(120) NULL,
	distrito varchar(120) NULL,
	tipo_local varchar(120) NULL,
	proveedor_flm varchar(150) NULL,
	atencion varchar(120) NULL,
	zona varchar(120) NULL,
	tipo_zona_flm varchar(120) NULL,
	propietario_de_torre varchar(150) NULL,
	propietario_de_piso varchar(150) NULL,
	tipo_estacion varchar(120) NULL,
	tipo_torre varchar(120) NULL,
	clasificacion_instalacion varchar(150) NULL,
	fecha_puesta_en_servicio date NULL,
	bucket varchar(80) NULL,
	sla varchar(80) NULL,
	tipo_vip varchar(80) NULL,
	criticidad_local varchar(80) NULL,
	observacion varchar(500) NULL,
	priorizacion varchar(80) NULL,
	ubigeotoa varchar(120) NULL,
	creation_user varchar(100) DEFAULT (((COALESCE(inet_client_addr()::text, 'local'::text) || '-'::text) || CURRENT_USER::text)) NULL,
	creation_date timestamp(0) DEFAULT clock_timestamp()::timestamp(0) without time zone NULL,
	creation_ip inet DEFAULT inet_client_addr() NULL
);