
CREATE TABLE ods.sftp_hm_consumo_suministro (
	num_recibo varchar(250) NOT NULL,
	cod_suministro varchar(250) NULL,
	tarifa varchar(10) NULL,
	pot_contr varchar(255) NULL,
	titularidad varchar(255) NULL,
	distribuidor varchar(255) NULL,
	fec_emision date NULL,
	fec_vencimiento date NULL,
	fec_lect_actual date NULL,
	fec_lect_anterior date NULL,
	per_consumo varchar(50) NULL,
	ea_lec_act_hp numeric(18, 2) NULL,
	ea_lec_act_fp numeric(18, 2) NULL,
	ea_lec_act_tot numeric(18, 2) NULL,
	ea_lec_ant_hp numeric(18, 2) NULL,
	ea_lec_ant_fp numeric(18, 2) NULL,
	ea_lec_ant_tot numeric(18, 2) NULL,
	ea_consumo_hp numeric(18, 2) NULL,
	ea_consumo_fp numeric(18, 2) NULL,
	ea_consumo_tot numeric(18, 2) NULL,
	ea_pu_hp numeric(18, 6) NULL,
	ea_pu_fp numeric(18, 6) NULL,
	ea_prec_unit_tot numeric(18, 6) NULL,
	ea_importe_hp numeric(18, 2) NULL,
	ea_importe_fp numeric(18, 2) NULL,
	ea_importe_tot numeric(18, 2) NULL,
	pot_lect_act_hp numeric(18, 2) NULL,
	pot_lect_act_fp numeric(18, 2) NULL,
	pot_lect_ant_hp numeric(18, 2) NULL,
	pot_lect_ant_fp numeric(18, 2) NULL,
	pot_reg_hp numeric(18, 2) NULL,
	pot_reg_fp numeric(18, 2) NULL,
	pot_gen_fact numeric(18, 2) NULL,
	pot_gen_pu numeric(18, 6) NULL,
	pot_gen_importe numeric(18, 2) NULL,
	pot_dist_fact numeric(18, 2) NULL,
	pot_dist_pu numeric(18, 6) NULL,
	pot_dist_importe numeric(18, 2) NULL,
	pot_bt6_pu numeric(18, 6) NULL,
	pot_bt6_monto numeric(18, 2) NULL,
	er_lec_act numeric(18, 2) NULL,
	er_lec_ant numeric(18, 2) NULL,
	er_cons numeric(18, 2) NULL,
	er_fact numeric(18, 2) NULL,
	er_pu numeric(18, 6) NULL,
	er_importe numeric(18, 2) NULL,
	calif_cliente varchar(100) NULL,
	dias_punta int4 NULL,
	horas_punta int4 NULL,
	factor_calif varchar(50) NULL,
	cargo_fijo numeric(18, 2) NULL,
	mantenimiento numeric(18, 2) NULL,
	alumbrado numeric(18, 2) NULL,
	recup_energia numeric(18, 2) NULL,
	mora numeric(18, 2) NULL,
	reconexion numeric(18, 2) NULL,
	ajuste_tarifa numeric(18, 2) NULL,
	dist_factura numeric(18, 2) NULL,
	ajuste_alumb numeric(18, 2) NULL,
	otros_afectos numeric(18, 2) NULL,
	base_imponible numeric(18, 2) NULL,
	igv numeric(18, 2) NULL,
	tot_periodo numeric(18, 2) NULL,
	electrif_rural numeric(18, 2) NULL,
	comp_distribucion numeric(18, 2) NULL,
	comp_generadora numeric(18, 2) NULL,
	comp_interrup numeric(18, 2) NULL,
	comp_calidad numeric(18, 2) NULL,
	comp_frec_ant numeric(18, 2) NULL,
	comp_frec_des numeric(18, 2) NULL,
	comp_serv numeric(18, 2) NULL,
	comp_norma_tec numeric(18, 2) NULL,
	comp_deuda_ant numeric(18, 2) NULL,
	comp_deuda_meses int4 NULL,
	comp_dev_reclamo numeric(18, 2) NULL,
	comp_nota_deb_cred numeric(18, 2) NULL,
	comp_aporte_reemb numeric(18, 2) NULL,
	comp_otros_inafectos numeric(18, 2) NULL,
	comp_redondeo_act_pos numeric(18, 2) NULL,
	comp_redondeo_act_neg numeric(18, 2) NULL,
	costo_medio numeric(18, 2) NULL,
	total_a_pagar numeric(18, 2) NULL,
	valor_venta numeric(18, 2) NULL,
	deuda_anterior numeric(18, 2) NULL,
	devolucion numeric(18, 2) NULL,
	fecha_liquidacion date NULL,
	creation_user varchar(100) DEFAULT (((COALESCE(inet_client_addr()::text, 'local'::text) || '-'::text) || CURRENT_USER::text)) NULL,
	creation_date timestamp(0) DEFAULT clock_timestamp()::timestamp(0) without time zone NULL,
	creation_ip inet DEFAULT inet_client_addr() NULL,
	CONSTRAINT sftp_hm_consumo_suministro_pkey PRIMARY KEY (num_recibo)
);